services:
  db:
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=movingpapa
      - MYSQL_USER=user
    volumes:
      - dbdata:/var/lib/mysql
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql:ro
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: unless-stopped
  movingpapa:
    image: ${DOCKER_REGISTRY-}movingpapa
    build:
      context: .
      dockerfile: MovingPapa/Dockerfile
    volumes:
      - aspnet_data:/root/.aspnet/

  webserver:
    depends_on:
      - phpmyadmin
      - movingpapa
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt

    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - certbot-etc/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/html --email michael.cheers8@gmail.com --agree-tos --no-eff-email -d movingpapa.com --force-renewal